apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
      - name: cv_container
        image: image_cv:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: cv
spec:
  selector:
    app: cv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
